Add logic to compare approver with committer.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,7 +5,12 @@ commands:
     description: "Validate whether deployment was properly approved."
     steps:
       - run: |
-          WORKFLOW_JOBS=$(curl -H "Circle-Token: $CIRCLECI_API_KEY" "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/job")
+          COMMITTED_BY=$(curl -H "Circle-Token: $CIRCLE_TOKEN" "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}" | jq -r .started_by)
+
+          COMMITTER=$(curl -H "Circle-Token: $CIRCLE_TOKEN" "https://circleci.com/api/v2/user/${COMMITTED_BY}")
+          COMMITTER_NAME=$(echo "$COMMITTER" | jq -r '"\(.name) (\(.login))"')
+
+          WORKFLOW_JOBS=$(curl -H "Circle-Token: $CIRCLE_TOKEN" "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/job")
           CURRENT_JOB_DEPENDENCIES=$(echo "$WORKFLOW_JOBS" | jq -cr ".items[] | select(.id == \"$CIRCLE_WORKFLOW_JOB_ID\") | .dependencies[]")
           APPROVAL_JOBS=$(echo "$WORKFLOW_JOBS" | jq -cr '.items[] | select(.type == "approval")')
 
@@ -25,9 +30,25 @@ commands:
             exit 1
           fi
 
-          APPROVER=$(curl -H "Circle-Token: $CIRCLECI_API_KEY" "https://circleci.com/api/v2/user/${APPROVED_BY}")
+          APPROVER=$(curl -H "Circle-Token: $CIRCLE_TOKEN" "https://circleci.com/api/v2/user/${APPROVED_BY}")
           APPROVER_NAME=$(echo "$APPROVER" | jq -r '"\(.name) (\(.login))"')
+          echo "Committer: $COMMITTER_NAME"
           echo "Approver: $APPROVER_NAME"
+          echo
+          if [ "$COMMITTER_NAME" == "null" || "$APPROVER_NAME" == "null" ]; then
+            echo "Could not verify identity of committer and/or approver!"
+            exit 1
+          fi
+
+          if [ "$COMMITTER_NAME" != "$APPROVER_NAME" ]; then
+            echo "Approval verified successfully!"
+              exit 0
+          else
+            echo "Approval verification failed.  Please ensure that deployments are approved by someone other than the committer."
+              exit 1
+          fi
+          
+            
 
 jobs:
   build-and-test:
